Repository owid/owid-grapher, pull requests merged in 2021-05, with the labels that each got.

#896 fix: make country selection top-to-bottom, left-to-right
  grapher/controls/EntitySelectorModal.scss
Labels: bug

#897 enhance: Shrink explorer title to reduce wasted space
  explorer/Explorer.scss
Labels: enhancement

#900 feat: StackedDiscreteBar charts tooltips and they show values inside bars
  grapher/chart/Tippy.tsx
  grapher/color/ColorUtils.test.ts
  grapher/color/ColorUtils.ts
  grapher/core/Grapher.tsx
  grapher/stackedCharts/StackedConstants.ts
  grapher/stackedCharts/StackedDiscreteBarChart.test.ts
  grapher/stackedCharts/StackedDiscreteBarChart.tsx
  grapher/stackedCharts/StackedUtils.test.ts
  grapher/stackedCharts/StackedUtils.ts
Labels: feature
